name: 'LaunchDarkly Outdated Feature Flags Reporter'
description: 'The action provide the feature flags that might be ready for removal'
author: 'Rufat Khaslarov'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
inputs:
  access-token:
    description: 'Launch Darkly Access Token with Read permissions at least'
    required: true
  project-key:
    description: 'Launch Darkly Project Key'
    required: true
  environment-key:
    description: 'Launch Darkly Project Environment'
    required: true
  maintainer-teams:
    description: 'Maintainer teams'
    required: true
  report-type:
    description: 'Report Type (Slack or Custom)'
    required: false
    default: 'default'
  slack-webhook:
    description: 'If Report Type is Slack, specify the Slack Webhook URL'
    required: false


# Define your outputs here.
outputs:
  feature-flags:
    description: 'Outdated Feature Flags Entities from Launch Darkly'

runs:
  using: node20
  main: dist/index.js
